/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gim-yeongjin' at '17. 4. 6 오후 2:46' with Gradle 2.14.1
 *
 * @author gim-yeongjin, @date 17. 4. 6 오후 2:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
