import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gim-yeongjin' at '17. 4. 6 오후 2:46' with Gradle 2.14.1
 *
 * @author gim-yeongjin, @date 17. 4. 6 오후 2:46
 */

public class Library {
    static public void main(String[] args) {
    	JSONObject a = new JSONObject();
    	a.put("name", "김떙떙");
    	a.put("phoneNumber", "01020661234");
    	
    	JSONArray array = new JSONArray();
    	array.add(a);
    	array.add(a);
    	array.add(a);
    	
    	String fileSave = array.toJSONString();
    	String fileRead = new String(fileSave);
    	
    	JSONParser parser = new JSONParser();
    	JSONObject fileRead = (JSONObject)parser.parse(fileRead);
    	System.out.println(fileSave);
    }
}
